// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH_4B04JCWSl100ftL0OAsTpm68bLOphI',
    appId: '1:638520660204:web:12fdf544e89464598315c9',
    messagingSenderId: '638520660204',
    projectId: 'waterlevel-ad823',
    authDomain: 'waterlevel-ad823.firebaseapp.com',
    databaseURL: 'https://waterlevel-ad823-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waterlevel-ad823.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOXMb6LLucDJe-V09q8k6CKeQQH9DZq8k',
    appId: '1:638520660204:android:5d1c7749f4ed1ad68315c9',
    messagingSenderId: '638520660204',
    projectId: 'waterlevel-ad823',
    databaseURL: 'https://waterlevel-ad823-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waterlevel-ad823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqqron7yn7Hb4mdDe_LH_5eIfjuDPlFwo',
    appId: '1:638520660204:ios:53edc5e8431ee8528315c9',
    messagingSenderId: '638520660204',
    projectId: 'waterlevel-ad823',
    databaseURL: 'https://waterlevel-ad823-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waterlevel-ad823.appspot.com',
    iosClientId: '638520660204-oc66fsjl9lnekg1j9543mlkp01gm9462.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterlevel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqqron7yn7Hb4mdDe_LH_5eIfjuDPlFwo',
    appId: '1:638520660204:ios:d5c607e05bd58bf88315c9',
    messagingSenderId: '638520660204',
    projectId: 'waterlevel-ad823',
    databaseURL: 'https://waterlevel-ad823-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waterlevel-ad823.appspot.com',
    iosClientId: '638520660204-s45v5uj2lumd90go08l0ckm9formdmg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterlevel.RunnerTests',
  );
}
